/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin on the JVM.
    id("org.jetbrains.kotlin.jvm").version("1.3.21")

    id("antlr")

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    implementation("org.jetbrains.kotlin:kotlin-stdlib:1.3.40")

    implementation("fr.inria.gforge.spoon:spoon-core:7.5.0-beta-21")

    implementation("org.antlr:antlr4-runtime:4.7.2")

    implementation("org.antlr:antlr4:4.7.2")

    antlr("org.antlr:antlr4:4.7.2")

    implementation("com.google.code.gson:gson:2.8.5")

    compile("org.neo4j:neo4j-ogm-core:3.2.14")

    compile("org.neo4j:neo4j-ogm-bolt-driver:3.2.14")
    compile("org.neo4j:neo4j-ogm-http-driver:3.2.14")
    compile("org.neo4j:neo4j-ogm-embedded-driver:3.2.14")
    compile("org.neo4j:neo4j:4.1.0")

    implementation("mysql:mysql-connector-java:8.0.16")

    implementation("org.slf4j:slf4j-simple:1.7.26")
    implementation("org.slf4j:slf4j-api:1.7.26")
}

application {
    // Define the main class for the application.
    mainClassName = "com.sudosan.AppKt"
}
